#!/usr/bin/env bash

set -e
# the following should update the scripts to be executable but I've found that sometimes I have to do this myself
chmod a+x ./scripts/brew-update.sh
chmod a+x ./scripts/mac-settings.sh
chmod a+x ./scripts/npm.sh
chmod a+x ./scripts/yarn.sh
chmod a+x ./scripts/zsh.sh

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
