# Fig pre block. Keep at the top of this file.
. "$HOME/.fig/shell/zshrc.pre.zsh"
# zmodload zsh/zprof
# source /usr/local/opt/chruby/share/chruby/chruby.sh
# source /usr/local/opt/chruby/share/chruby/auto.sh
source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle colored-man-pages
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle z
antigen bundle docker-compose
antigen bundle npm

case `uname` in
  Darwin)
    # Commands for OS X go here
    antigen bundle osx
  ;;
  Linux)
    # Commands for Linux go here
  ;;
esac

antigen bundle ~/.oh-my-zsh/custom/themes smcgee31.zsh-theme --no-local-clone

# workaround for https://github.com/zsh-users/antigen/issues/675
THEME=smcgee31
antigen list | grep $THEME; if [ $? -ne 0 ]; then antigen theme $THEME; fi
# antigen theme robbyrussell

antigen apply


source ~/.aliases

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source ~/.profile

source ~/smcgee31.zsh-theme

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true


# GuideCX specific stuff >>>
function docker:clear {
  docker ps -aq | \
    while read id; do docker stop $id && docker rm $id; done
}

function docker:nuke {
  docker:clear && \
  docker image ls | \
    tr -s ' ' | \
    awk '{print $3}' | \
    while read id; do docker image rm $id --force; done
}

export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.0/bin:$PATH"
eval "$(rbenv init -)"

export PATH="$PATH:${HOME}/Documents/Developer/flutter/bin"

# Fig post block. Keep at the bottom of this file.
. "$HOME/.fig/shell/zshrc.post.zsh"
